version: '3.8'

services:
  minecraft-server:
    build: .
    image: itzg/minecraft-server
    container_name: atm9
    environment:
      CF_API_KEY: '$2a$10$3iDVGIPkrjqtJTc3eBOKl.OrdzFTGRSClsmL0eElP8nRaqQKZF7pO'
      CF_SLUG: 'all-the-mods-9'
      EULA: 'TRUE'
      TYPE: 'AUTO_CURSEFORGE'
      VERSION: '1.20.1'
      MEMORY: '12G'
      ENABLE_ROLLING_LOGS: 'true'
      USE_AIKAR_FLAGS: 'true'
    volumes:
      - ./data:/data
    ports:
      - '25569:25565'
      - '19569:19565'
      - '24454:24454'
    restart: always
